#!/bin/bash
#
# Script to change pihole dns settings when vpn is up/down

PROTONVPN_DNS=10.8.8.1
CLOUDFLARE_DNS=1.1.1.1

case "$script_type" in
  "up")
    NEW_DNS=${PROTONVPN_DNS}
    ;;
  "down")
    NEW_DNS=${CLOUDFLARE_DNS}
    ;;
  *)
    echo "dns_change script failure: up|down where not passed in '$script_type'"
    exit 1
    ;;
esac
sudo sed -i "s/PIHOLE_DNS_1=.*/PIHOLE_DNS_1=${NEW_DNS}/" /etc/pihole/setupVars.conf
pihole restartdns
