#!/bin/bash
# 
# Script to kickstart pihole specific configurations

echo
echo "------------------------------------------------------"
echo "Beginning Pihole script"
echo "------------------------------------------------------"
echo
# shellcheck disable=SC2034
# pihole_original_ip="192.168.2.200"
# shellcheck disable=SC2034
# pihole_original_user="choco"

echo "------------------------------------------------------"
echo "Disabling the screen of the pi on boot via init.d script"
echo "------------------------------------------------------"
# disabling the screen of the pi on boot via init.d script
sudo cp ../common/tvoff /etc/init.d/tvoff
sudo chmod 755 /etc/init.d/tvoff
sudo update-rc.d tvoff defaults


# echo "------------------------------------------------------"
# echo "Copying original pihole settings from original and running pihole"
# echo "------------------------------------------------------"
# # copying the ssh public key
# ssh-copy-id ${pihole_original_user}@${pihole_original_ip}
# # copying all the pihole configs to tmp folders in ${HOME}
# scp -r ${pihole_original_user}@${pihole_original_ip}:/etc/dnsmasq.d/ ~/
# mkdir ~/pihole
# scp ${pihole_original_user}@${pihole_original_ip}:/etc/pihole/setupVars.conf ~/pihole
# scp ${pihole_original_user}@${pihole_original_ip}:/etc/pihole/adlists.list ~/pihole
# scp ${pihole_original_user}@${pihole_original_ip}:/etc/pihole/whitelist.txt ~/pihole
# scp ${pihole_original_user}@${pihole_original_ip}:/etc/pihole/blacklist.txt ~/pihole
# scp ${pihole_original_user}@${pihole_original_ip}:/etc/pihole/wildcardblocking.txt ~/pihole
#
# # Modifying the IP from the new pihole
# NEW_IP=$(hostname -I | awk '{print $1}')
# sudo sed -i "s/IPV4_ADDRESS=.*/IPV4_ADDRESS=${NEW_IP}\/24/" ~/pihole/setupVars.conf
# sudo sed -i "s/DHCP_ROUTER=.*/DHCP_ROUTER=${NEW_IP}/" ~/pihole/setupVars.conf
# sudo sed -i "s/dhcp-option=option:router,.*/dhcp-option=option:router,${NEW_IP}/" ~/dnsmasq.d/02-pihole-dhcp.conf
#
# #moving configuration files to the final folders
# sudo mv ~/pihole/ /etc/
# sudo mv ~/dnsmasq.d/ /etc/
# #sudo chown pihole:pihole /etc/pihole/
# sudo chown -R root:root /etc/dnsmasq.d/


echo "------------------------------------------------------"
echo "Installing pihole"
echo "------------------------------------------------------"
# installing pihole required package
sudo apt install bc
# install pihole
curl -L https://install.pi-hole.net | sudo bash /dev/stdin --unattended

# Checking that the installation was completed
if ! command -v pihole &> /dev/null
then
  # if not, modify /etc/resolv.conf and retry
  echo "------------------------------------------------------"
  echo "Retrying pihole installation in 10 seconds, please wait..."
  sleep 10
  echo "Now proceeding with pihole installation retry"
  echo "------------------------------------------------------"
  echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
  curl -L https://install.pi-hole.net | sudo bash /dev/stdin --unattended
fi
