#!/bin/bash
#
# Notification script

set -e          # stop on errors
set -u          # stop on unset variables
set -o pipefail # stop on pipe failures

usage(){
  echo "Usage: $(basename "$0") webhook-id path_to_script all_arguments"
}

E_NOARGS=85
wh_regex="T\w*\/B\w*\/\w*"
if [ -z ${1+x} ] || [ -z ${2+x} ]; then
  usage
  exit "$E_NOARGS"
elif ! [[ $1 =~ $wh_regex ]]; then
  echo "Webhook format invalid. Expected format $wh_regex"
  usage
  exit 0
fi

wh=$1
webmonitor_hook="https://hooks.slack.com/services/$wh"

script_path=$2
script_args="${@:3}"
execution_result=$($script_path "$script_args")

content="{\"text\":\"\`$(hostname)\` - ${script_path} executed\n \`\`\`${execution_result}\`\`\` \"}"
echo "$(date) - $(basename "$0") - Webhook result: $(curl -s -X POST -H 'Content-type: application/json' --data "${content}" "$webmonitor_hook")"