#! /bin/bash
# /etc/init.d/tvoff

### BEGIN INIT INFO
# Provides:          tvoff
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script to disable HDMI output on boot
### END INIT INFO

sudo /usr/bin/tvservice -o