#!/usr/bin/env bash
# 
# Script to update periodically the pi

echo [$(date)] " update started"
sudo apt-get --yes clean
sudo apt-get --yes update && sudo apt-get --yes upgrade && sudo apt-get --yes full-upgrade
sudo apt-get --yes autoremove
sudo apt-get --yes autoclean
sudo reboot
