#!/bin/bash
# 
# Script to kickstart hifipi specific configurations

set -e          # stop on errors
set -u          # stop on unset variables
set -o pipefail # stop on pipe failures

echo
echo "------------------------------------------------------"
echo "Beginning HifiPI script"
echo "------------------------------------------------------"
echo

echo "------------------------------------------------------"
echo "removing USB audio deprioritization"
echo "------------------------------------------------------"
echo
# remove USB audio deprioritization
sudo sed -e '/snd-usb-audio/ s/^#*/#/' -i /lib/modprobe.d/aliases.conf
# reloading systemd modules
sudo systemctl restart systemd-modules-load.service

echo
echo "------------------------------------------------------"
echo "Cloning and building shairport"
echo "------------------------------------------------------"
echo
# installing required dependencies
sudo apt -y install autoconf automake avahi-daemon build-essential libasound2-dev libavahi-client-dev libconfig-dev libdaemon-dev libpopt-dev libssl-dev libtool xmltoman alsa-utils
# cloning and building shairport
git clone https://github.com/mikebrady/shairport-sync.git
cd shairport-sync || exit
autoreconf -i -f
./configure --with-alsa --with-avahi --with-ssl=openssl --with-systemd --with-metadata
make
sudo make install
sudo systemctl enable shairport-sync
amixer sset PCM,0 100%
cd ..
sudo rm -rf shairport-sync

echo
echo "------------------------------------------------------"
echo "Configuring raspotify"
echo "------------------------------------------------------"
echo
# installing required dependencies
sudo apt -y install apt-transport-https
# Add raspotify repo and its GPG key
curl -sSL https://dtcooper.github.io/raspotify/key.asc | sudo apt-key add -v -
echo 'deb https://dtcooper.github.io/raspotify raspotify main' | sudo tee /etc/apt/sources.list.d/raspotify.list
# Update packages after importing
sudo apt-get update
# install raspspotify
sudo apt -y install raspotify

echo "------------------------------------------------------"
echo "Installing mpd - music daemon to play streams"
echo "------------------------------------------------------"
sudo apt install -y mpd
mpd_conf="/etc/mpd.conf"

# modifying mpd configuration
# allowing any host to connect
sudo sed -e '/bind_to_address/ s/^#*/#/' -i ${mpd_conf}
# enabling mdns announcement of the device
echo 'zeroconf_enabled		"yes"' | sudo tee -a ${mpd_conf} > /dev/null
echo 'zeroconf_name		"hifipi-mpd"' | sudo tee -a ${mpd_conf} > /dev/null

#echo "------------------------------------------------------"
#echo "RetroPie Installation"
#echo "------------------------------------------------------"
#echo
# Configuring locale required for retropie
#sudo update-locale LANGUAGE=en_US:en
#sudo update-locale LANGUAGE=en_US:en
# Adding dependencies
#sudo apt -y install lsb-release
# Copying repo and and installing
#git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git ~/RetroPie-Setup
#chmod +x ~/RetroPie-Setup/retropie_setup.sh
#sudo ~/RetroPie-Setup/retropie_setup.sh
# Adding autologin to retropie
#f="/etc/systemd/system/getty@tty1.service.d/autologin.conf"
#sudo mkdir -p -- "${f%/*}" && echo -e "[Service]\nExecStart=-/sbin/agetty --autologin ${USER} --noclear %I 38400 linux" | sudo tee "$f"
#sudo systemctl enable getty@tty1.service