#!/bin/bash
# 
# Script to kickstart hifipi specific configurations

echo
echo "------------------------------------------------------"
echo "Beginning HifiPI script"
echo "------------------------------------------------------"
echo
echo
echo "------------------------------------------------------"
echo "Cloning and building shairport"
echo "------------------------------------------------------"
echo
#cloning and building shairport
git clone https://github.com/mikebrady/shairport-sync.git
cd shairport-sync
autoreconf -i -f
./configure --with-alsa --with-avahi --with-ssl=openssl --with-systemd --with-metadata
make
sudo make install
sudo systemctl enable shairport-sync
amixer sset PCM,0 100%

echo
echo "------------------------------------------------------"
echo "Configuring raspotify"
echo "------------------------------------------------------"
echo
#Add raspotify repo and its GPG key
curl -sSL https://dtcooper.github.io/raspotify/key.asc | sudo apt-key add -v -
echo 'deb https://dtcooper.github.io/raspotify raspotify main' | sudo tee /etc/apt/sources.list.d/raspotify.list

#install raspspotify
sudo apt-get update
sudo apt-get -y install raspotify

echo
echo "------------------------------------------------------"
echo "Creating an alias to act as a relay for downloading torrents"
echo "------------------------------------------------------"
echo
#create alias to download files easily
echo "alias descargar='transmission-remote 192.168.2.204:9091 --auth=choco:popstock -a '" >> .bashrc
#changing access to bashrc
chmod 600 .bashrc
