#!/bin/bash
#
# Script to kickstart devpi specific configurations

set -e          # stop on errors
set -u          # stop on unset variables
set -o pipefail # stop on pipe failures

echo
echo "------------------------------------------------------"
echo "Beginning HifiPI script"
echo "------------------------------------------------------"
echo

echo "Nothing specific to the devpi"