#!/bin/bash
# 
# Script to kickstart dockassist specific configurations

echo
echo "------------------------------------------------------"
echo "Beginning Dockassist script"
echo "------------------------------------------------------"
echo

echo "------------------------------------------------------"
echo "Disabling the screen of the pi on boot via init.d script"
echo "------------------------------------------------------"
# disabling the screen of the pi on boot via init.d script
sudo cp ../common/tvoff /etc/init.d/tvoff
sudo chmod 755 /etc/init.d/tvoff
sudo update-rc.d tvoff defaults

echo
echo "------------------------------------------------------"
echo "Docker installation"
echo "------------------------------------------------------"
echo
# installing required dependencies
sudo apt-get install apt-transport-https ca-certificates software-properties-common -y
# installing docker
curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
# allowing user to run docker
sudo usermod -aG docker ${USER}
# installing sources
#sudo curl https://download.docker.com/linux/raspbian/gpg
#deb https://download.docker.com/linux/raspbian/ stretch stable
sudo systemctl start docker.service
# reloading the shell to reload user permissions
sudo -iu ${USER}
docker info

echo
echo "------------------------------------------------------"
echo "HomeAssistant installation"
echo "------------------------------------------------------"
echo
# installing required dependencies
sudo apt-get update
sudo apt-get install -y apparmor-utils avahi-daemon dbus jq network-manager socat
# disabling modemmanager
sudo systemctl disable ModemManager
sudo systemctl stop ModemManager
# downloading and running home assist
ha_name="home-assistant"
docker run --init -d --restart unless-stopped --name="${ha_name}" -v /home/${USER}/homeassistant:/config --net=host homeassistant/raspberrypi4-homeassistant:stable
# Now lets install hacs https://hacs.xyz/
docker exec -i ${ha_name} wget -q -O - https://hacs.xyz/install | bash -
